apiVersion: apps/v1
kind: Deployment
metadata:
  name: hodl-backend
  labels:
    app.kubernetes.io/name: hodl
    app.kubernetes.io/instance: hodl-backend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: hodl
      app.kubernetes.io/instance: hodl-backend
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hodl
        app.kubernetes.io/instance: hodl-backend
    spec:
      containers:
        - name: hodl-backend
          image: docker.io/bennynwh/hodl-backend:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: 600Mi
              cpu: 1000m
            requests:
              memory: 300Mi
              cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hodl-web
  labels:
    app.kubernetes.io/name: hodl
    app.kubernetes.io/instance: hodl-web
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: hodl
      app.kubernetes.io/instance: hodl-web
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hodl
        app.kubernetes.io/instance: hodl-web
    spec:
      containers:
        - name: hodl-web
          image: docker.io/bennynwh/hodl-web:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: 600Mi
              cpu: 1000m
            requests:
              memory: 300Mi
              cpu: 500m
