apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ./ingress.yaml
  - ./runtime/cert/cluster-issuer.yaml

namespace: hodl

patches:
  - path: deployment.patch.yaml
    target:
      kind: Deployment
  - path: hodl-backend.patch.yaml
    target:
      kind: Deployment
      name: hodl-backend
  - path: hodl-web.patch.yaml
    target:
      kind: Deployment
      name: hodl-web
