name: web ci

on:
  push:
     branches:
      - main
      
jobs:
  deploy:
    name: Deploy new image
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2

    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    -
      name: Build image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./web
        push: false
        load: true
        tags: hodl-web

    -
      name: Save image
      run: |-
        docker images
        docker save -o ./hodl-web.tar.gz hodl-web

    -
      name: Upload image
      uses: appleboy/scp-action@master
      with:
        host: api.bible-story.fun-mushroom.com
        username: deployer
        key: ${{ secrets.DEPLOY_KEY }}
        port: 22
        source: ./hodl-web.tar.gz
        target: /home/deployer/
        
    -
      name: Load image & re-run
      uses: appleboy/ssh-action@master
      with:
        host: api.bible-story.fun-mushroom.com
        username: deployer
        key: ${{ secrets.DEPLOY_KEY }}
        port: 22
        script: |
          docker load -i /home/deployer/hodl-web.tar.gz
          docker stop hodl-web || true
          docker rm hodl-web || true
          docker run -dit --name hodl-web -p 3000 --network caddy_default hodl-web

